admin_token: 134554321

config_file: /etc/keystone/keystone.conf

keystone_dbsync_host: foonova-0
keystone:
  host: 192.168.250.206
  admin_port: 35357
  service_port: 5000
  version: v2.0
  # 2do service_id tengo que convertirlo en fact.
  # service_id: 4f82df7699f24f3d829849fc60e04924
  region: SpainTest
  admin_password: admin1

keystone_config:
  auth_uri: "http://{{keystone.host}}:{{keystone.service_port}}"
  auth_url: "http://{{keystone.host}}:{{keystone.admin_port}}"
  project_domain_id: default
  user_domain_id: default
  project_name: service
